config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :users
  root :to => 'tasks#index'
  
  get '/list_tasks' => 'tasks#list_tasks'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user, class_name: "User", foreign_key: "user_id"
	belongs_to :responsable, class_name: "User", foreign_key: "responsable_id"
  	

	validates :hours, numericality: { only_integer: true }
	validates_presence_of :title
	#Fechas
  	def self.by_person(user_id)
    	where("user_id = :person_id OR responsable_id = :person_id", person_id: responsable_id)
  	end 
	validate :valid_date

	def valid_date
	  if (start_time && end_time) && (end_time < start_time)
	    errors.add(:end_time, "must be later than Start Time")
	  end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable
	has_many :tasks
	validates :username, :presence => true
  validates :name, :presence => true
  validates :lastname, :presence => true
	has_attached_file :profile, :styles => { :medium => "300x300>" , :mini => "40x40" , :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :profile, :content_type => /\Aimage\/.*\Z/  	
  
  def tasks
    Task.by_person(self.id)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username, :name, :lastname, :email, :password, :password_confirmation, :profile)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:username, :name, :lastname, :email, :password, :password_confirmation, :current_password, :biography, :location, :profile)
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.order(:end_time => :asc)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks}
    end
    
  end

  respond_to :html
  
  def list_tasks
    @tasks = Task.all
    respond_with(@tasks)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :hours, :start_time, :end_time, :check, :user_id, :responsable_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_responsable
      @responsable = User.find_by(username: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :lastname, :profile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flass_class(type)
    case type
      when :success then "success"
      when :error   then "warning"
      when :alert   then "warning"
      when :notice  then ""
      else "info"
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to 'Trello-Parcial', root_path %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon">
          <a href="#"><span>Menu</span></a>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <li class="divider">
          </li>
          <li>
            <%= link_to t('Users'), users_path %>          </li>
            <%if user_signed_in? %>
            <li>
            <%= link_to t('Mis tareas'), list_tasks_path %>
            </li>
            <% end %>
          </ul>
          <ul class="right">
            <% if user_signed_in? %>
            <li class="avatar">
              <% if current_user.profile.file? %>
              <%= image_tag current_user.profile.url(:mini), class: "round" %>
              <% end %>
            </li>
            <li>
              <%= link_to current_user.name, edit_user_registration_path %>
            </li>
            <li>
              <%= link_to t('Sign Out'), destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
            <li class="active">
              <%= link_to t('Sign Up'), new_user_registration_path %>
            </li>
            <li>
              <%= link_to t('Sign In'), new_user_session_path %>
            </li>
            <% end %>
          </ul>        

        </section>
      </nav>
    </div>
    <br>

    <div class="row">
      <div class="columns large-12">

        <% flash.each do |type, message| %>
        <div data-alert class="alert-box radius <%= flass_class type %>">
          <%= message %>
          <a href="#" class="close">&times;</a>
        </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
  </html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.number_field :hours %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.date_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.date_select :end_time %>
  </div>
  <div class="field">
    <%= f.label "Finished" %> <br />
    <%= f.check_box :check %> <br />
  </div>
  <div class="field">
    <%= f.label "Responsable" %> <br />
    <%= f.collection_select(:responsable_id, User.all, :id, :username) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>
  <div class="row">
    <div class="columns large-3">
      <fieldset>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hours</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Finished</th>      
      <th>User</th>
      <th>Responsable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
        <% if task.check==false %>    
      <tr>
        <td><%= task.title %></td>
        <td><%= task.hours %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= task.check %></td>
        <td><%= task.user.name %></td>
        <td><%= task.responsable.name %></td>
        <td><%= link_to 'Show', task %></td>
        <%if user_signed_in? %>
        <%if task.user.id==current_user.id%>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>        
      </fieldset>
    </div>

    <div class="columns large-3">
      <fieldset>
 <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hours</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Finished</th>      
      <th>User</th>
      <th>Responsable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
        <% if task.check==true %>    
      <tr>
        <td><%= task.title %></td>
        <td><%= task.hours %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= task.check %></td>
        <td><%= task.user.name %></td>
        <td><%= task.responsable.name %></td>
        <td><%= link_to 'Show', task %></td>
        <%if user_signed_in? %>
        <%if task.user.id==current_user.id%>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
       
      </fieldset>
    </div>
  </div>


<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/list_tasks.html.erb
  <div class="row">
    <div class="columns large-3">
      <fieldset>

<h3>Listing tasks</h3>

  <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hours</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Finished</th>      
      <th>User</th>
      <th>Responsable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.user_id == current_user.id %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.hours %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= task.check %></td>
        <td><%= task.user.name %></td>
        <td><%= task.responsable.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
      </fieldset>
    </div>

    <div class="columns large-3">
      <fieldset>

  <h3>Assigned Tasks:</h3>
  <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hours</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Finished</th>      
      <th>User</th>
      <th>Responsable</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.responsable == current_user.id %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.hours %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= task.check %></td>
        <td><%= task.user.name %></td>
        <td><%= task.responsable.name %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
      </fieldset>
    </div>
  </div>


<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @task.hours %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @task.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @task.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user.name %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @task.responsable.name %>
</p>

<%= link_to 'Back', tasks_path %>

app/views/tasks/taskLists.html.erb
<h1>Listing tasks</h1>

<div class="columns large-12">
  <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hours</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Finished</th>      
      <th>User</th>
      <th>Responsable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.author == current_user.id %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.hours %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= task.check %></td>
        <td><%= task.user.name %></td>
        <td><%= task.responsable.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<div class="columns large-12">
  <h3>Assigned Tasks:</h3>
  <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hours</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Finished</th>      
      <th>User</th>
      <th>Responsable</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if task.responsible == current_user.id %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.hours %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= task.check %></td>
        <td><%= task.user.name %></td>
        <td><%= task.responsable.name %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>


<br>

<%= link_to 'New Task', new_task_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Back', users_path %>